steps:
  # 1) Build (unique image tag)
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/pdf-polish-frontend:$BUILD_ID"
      - "--build-arg"
      - "VITE_API_BASE_URL=https://pdf-polish-api-722522316664.northamerica-northeast1.run.app"
      - "./frontend"

  # 2) Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/pdf-polish-frontend:$BUILD_ID"]

  # 3) Deploy to Cloud Run ✅ (this is the missing piece)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "pdf-polish-frontend"
      - "--image"
      - "gcr.io/$PROJECT_ID/pdf-polish-frontend:$BUILD_ID"
      - "--region"
      - "northamerica-northeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--quiet"

images:
  - "gcr.io/$PROJECT_ID/pdf-polish-frontend:$BUILD_ID"