"""create core tables

Revision ID: 74363508ce70
Revises: 
Create Date: 2026-01-15 15:15:03.791498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74363508ce70'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_emails_gmail_message_id'), 'inbound_emails', ['gmail_message_id'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inbound_email_id', sa.UUID(), nullable=True),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('property_address', sa.Text(), nullable=True),
    sa.Column('customer_name', sa.Text(), nullable=True),
    sa.Column('customer_email', sa.String(length=320), nullable=True),
    sa.Column('invoice_number', sa.String(length=64), nullable=True),
    sa.Column('quote_number', sa.String(length=64), nullable=True),
    sa.Column('job_report_number', sa.String(length=64), nullable=True),
    sa.Column('original_s3_key', sa.Text(), nullable=False),
    sa.Column('styled_draft_s3_key', sa.Text(), nullable=True),
    sa.Column('final_s3_key', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inbound_email_id'], ['inbound_emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_customer_email', 'documents', ['customer_email'], unique=False)
    op.create_index('idx_documents_doc_type', 'documents', ['doc_type'], unique=False)
    op.create_index('idx_documents_invoice_number', 'documents', ['invoice_number'], unique=False)
    op.create_index('idx_documents_job_report_number', 'documents', ['job_report_number'], unique=False)
    op.create_index('idx_documents_quote_number', 'documents', ['quote_number'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_table('quote_decisions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('po_number', sa.String(length=128), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_by_email', sa.String(length=320), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('send_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('ses_message_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('provider_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_send_jobs_ses_message_id', 'send_jobs', ['ses_message_id'], unique=False)
    op.create_index('idx_send_jobs_status', 'send_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_send_jobs_document_id'), 'send_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_send_jobs_ses_message_id'), 'send_jobs', ['ses_message_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('send_job_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['send_job_id'], ['send_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_log', ['action'], unique=False)
    op.create_index('idx_audit_document_id', 'audit_log', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_document_id', table_name='audit_log')
    op.drop_index('idx_audit_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_send_jobs_ses_message_id'), table_name='send_jobs')
    op.drop_index(op.f('ix_send_jobs_document_id'), table_name='send_jobs')
    op.drop_index('idx_send_jobs_status', table_name='send_jobs')
    op.drop_index('idx_send_jobs_ses_message_id', table_name='send_jobs')
    op.drop_table('send_jobs')
    op.drop_table('quote_decisions')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_quote_number', table_name='documents')
    op.drop_index('idx_documents_job_report_number', table_name='documents')
    op.drop_index('idx_documents_invoice_number', table_name='documents')
    op.drop_index('idx_documents_doc_type', table_name='documents')
    op.drop_index('idx_documents_customer_email', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_inbound_emails_gmail_message_id'), table_name='inbound_emails')
    op.drop_table('inbound_emails')
    # ### end Alembic commands ###
